<?php

$data = [
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Bellissimo Appartamento nel Centro',
        'slug' => 'bellissimo-appartamento-centro',
        'description' => 'Un appartamento spazioso e moderno nel cuore della città.',
        'price' => 50,
        'square_meters' => 80,
        'num_of_room' => 3,
        'num_of_bed' => 2,
        'num_of_bathroom' => 1,
        'address' => 'Via Emilio Cornalia 12, 20124 Milano',
        'lat' => 45.4829,
        'lon' => 9.1971,
        'image_path' => 'apartment1.jpg',
        'visible' => false,
    ],
    [
        'type_id' => 2,
        'user_id' => 2,
        'title' => 'Vista Mare Appartamento Deluxe',
        'slug' => 'vista-mare-appartamento-deluxe',
        'description' => 'Lussuoso appartamento con una vista mozzafiato sul mare.',
        'price' => 200,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'address' => 'Via Statuto 21, 20121 Milano',
        'lat' => 45.4771,
        'lon' => 9.1851,
        'image_path' => 'apartment2.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 3,
        'user_id' => 3,
        'title' => 'Condominio Elegante con Giardino',
        'slug' => 'condominio-elegante-giardino',
        'description' => 'Appartamento situato in un condominio elegante con un bellissimo giardino comune.',
        'price' => 180,
        'square_meters' => 100,
        'num_of_room' => 3,
        'num_of_bed' => 2,
        'num_of_bathroom' => 2,
        'address' => 'Viale Bianca Maria 41, 20122 Milano',
        'lat' => 45.4670,
        'lon' => 9.2057,
        'image_path' => 'apartment3.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 4,
        'user_id' => 4,
        'title' => 'Villetta a Schiera con Giardino',
        'slug' => 'villetta-schiera-giardino',
        'description' => 'Villetta a schiera con spazioso giardino privato, perfetto per famiglie.',
        'price' => 150,
        'square_meters' => 110,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'address' => 'Via Morimondo 9, 20143 Milano',
        'lat' => 45.4462,
        'lon' => 9.1525,
        'image_path' => 'apartment4.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 2,
        'user_id' => 5,
        'title' => 'Appartamento Storico nel Cuore della Città Vecchia',
        'slug' => 'appartamento-storico-citta-vecchia',
        'description' => 'Appartamento con charme storico situato nel cuore della città vecchia, vicino a monumenti e luoghi di interesse.',
        'price' => 220,
        'square_meters' => 150,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'address' => 'Via San Rocco 18, 27010 Siziano',
        'lat' => 45.3164,
        'lon' => 9.2021,
        'image_path' => 'apartment5.jpg',
        'visible' => false,
    ],
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Appartamento Moderno con Vista Panoramica',
        'slug' => 'appartamento-moderno-vista-panoramica',
        'description' => 'Un appartamento moderno con una vista panoramica mozzafiato sulla città.',
        'price' => 180,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'address' => 'Via Ludovico Ariosto 44, 22060 Cabiate',
        'lat' => 45.6705,
        'lon' => 9.1727,
        'image_path' => 'apartment6.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 2,
        'title' => 'Loft Chic nel Cuore della Città',
        'slug' => 'loft-chic-citta',
        'description' => 'Un loft elegante e moderno situato nel centro della città, vicino ai principali centri di interesse.',
        'price' => 250,
        'square_meters' => 180,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'address' => 'Vicolo Magenta 10, 20014 Nerviano',
        'lat' => 45.5500,
        'lon' => 8.9716,
        'image_path' => 'apartment7.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 3,
        'title' => 'Appartamento di Lusso con Piscina Privata',
        'slug' => 'appartamento-lusso-piscina-privata',
        'description' => 'Un appartamento di lusso con piscina privata, ideale per una vacanza di relax.',
        'price' => 300,
        'square_meters' => 220,
        'num_of_room' => 6,
        'num_of_bed' => 5,
        'num_of_bathroom' => 4,
        'address' => 'Via Brolo 42, 21040 Uboldo',
        'lat' => 45.6125,
        'lon' => 9.0017,
        'image_path' => 'apartment8.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 4,
        'title' => 'Casa Vacanze con Accesso Privato alla Spiaggia',
        'slug' => 'casa-vacanze-accesso-privato-spiaggia',
        'description' => 'Una casa vacanze con accesso privato alla spiaggia, perfetta per una vacanza al mare.',
        'price' => 280,
        'square_meters' => 200,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'address' => 'Via Madonna 1, 20005 Pogliano Milanese',
        'lat' => 45.5331,
        'lon' => 8.9879,
        'image_path' => 'apartment9.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 4,
        'user_id' => 5,
        'title' => 'Appartamento con Vista Panoramica sulle Montagne',
        'slug' => 'appartamento-vista-panoramica-montagne',
        'description' => 'Un accogliente appartamento con una vista mozzafiato sulle montagne circostanti.',
        'price' => 150,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'address' => 'Via 4 Novembre 23, 20060 Masate',
        'lat' => 45.5691,
        'lon' => 9.4629,
        'image_path' => 'apartment10.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Elegante Residenza nel Cuore della Città',
        'slug' => 'elegante-residenza',
        'description' => 'Un rifugio raffinato che incarna l\'essenza del lusso e del comfort urbano. Questo appartamento esclusivo offre non solo una posizione centralissima, ma anche un ambiente sofisticato e accogliente che vi farà sentire a casa lontano da casa.',
        'price' => 120,
        'square_meters' => 80,
        'num_of_room' => 5,
        'num_of_bed' => 2,
        'num_of_bathroom' => 1,
        'address' => 'Viale di Porta Vercellina 12, 20123 Milano',
        'lat' => 45.4645,
        'lon' => 9.1652,
        'image_path' => 'pexels-curtis-adams-12119203.jpg',
        'visible' => false,
    ],
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Raffinato Loft nel Centro Storico',
        'slug' => 'raffinato-loft-centro-storico',
        'description' => 'Un appartamento unico nel suo genere nel cuore pulsante della città. Questo spazio affascinante fonde stili e influenze diverse, creando un\'atmosfera che cattura l\'attenzione e stimola la creatività.',
        'price' => 90,
        'square_meters' => 140,
        'num_of_room' => 3,
        'num_of_bed' => 2,
        'num_of_bathroom' => 1,
        'address' => 'Via Arena 13, 20123 Milano',
        'lat' => 45.4556,
        'lon' => 9.1792,
        'image_path' => 'pexels-dada-design-12281846.jpg',
        'visible' => false,
    ],
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Sospeso tra Cielo e Città: L\'Appartamento Perfetto',
        'slug' => 'appartamento-perfetto',
        'description' => 'Un appartamento che unisce il fascino del passato con il comfort moderno, creando un\'atmosfera unica nel cuore della città. Questa residenza offre un\'eleganza senza tempo e una posizione strategica per esplorare le bellezze storiche e culturali circostanti.',
        'price' => 100,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 2,
        'num_of_bathroom' => 1,
        'address' => 'Via Santa Sofia 24, 20122 Milano',
        'lat' => 45.4569,
        'lon' => 9.1898,
        'image_path' => 'pexels-max-rahubovskiy-7546551.jpg',
        'visible' => false,
    ],
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Magico Rifugio nel Labirinto Urbano',
        'slug' => 'magico-rifugio',
        'description' => 'Un rifugio di lusso che trasuda eleganza e stile nel centro vitale della città. Questo appartamento offre un\'esperienza di soggiorno straordinaria, accogliendo gli ospiti in un ambiente raffinato e confortevole.',
        'price' => 120,
        'square_meters' => 100,
        'num_of_room' => 2,
        'num_of_bed' => 2,
        'num_of_bathroom' => 2,
        'address' => 'Corso di Porta Vittoria 10, 20122 Milano',
        'lat' => 45.4619,
        'lon' => 9.1986,
        'image_path' => 'pexels-max-rahubovskiy-7546645.jpg',
        'visible' => true,
    ]


];

return $data;
