<?php

$data = [
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Bellissimo Appartamento nel Centro',
        'slug' => 'bellissimo-appartamento-centro',
        'description' => 'Un appartamento spazioso e moderno nel cuore della città.',
        'price' => 50,
        'square_meters' => 80,
        'num_of_room' => 3,
        'num_of_bed' => 2,
        'num_of_bathroom' => 1,
        'address' => 'Via Roma 123, 00059 Roma',
        'lat' => 41.7458,
        'lon' => 12.6508,
        'image_path' => 'apartment1.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 2,
        'user_id' => 2,
        'title' => 'Vista Mare Appartamento Deluxe',
        'slug' => 'vista-mare-appartamento-deluxe',
        'description' => 'Lussuoso appartamento con una vista mozzafiato sul mare.',
        'price' => 200,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'address' => 'Calle del Mar 45, 08001 Barcelona',
        'lat' => 41.3833,
        'lon' => 2.1833,
        'image_path' => 'apartment2.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 3,
        'user_id' => 3,
        'title' => 'Condominio Elegante con Giardino',
        'slug' => 'condominio-elegante-giardino',
        'description' => 'Appartamento situato in un condominio elegante con un bellissimo giardino comune.',
        'price' => 180,
        'square_meters' => 100,
        'num_of_room' => 3,
        'num_of_bed' => 2,
        'num_of_bathroom' => 2,
        'address' => 'Rue de la Paix 15, 75002 Parigi',
        'lat' => 48.8695,
        'lon' => 2.3312,
        'image_path' => 'apartment3.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 4,
        'user_id' => 4,
        'title' => 'Villetta a Schiera con Giardino',
        'slug' => 'villetta-schiera-giardino',
        'description' => 'Villetta a schiera con spazioso giardino privato, perfetto per famiglie.',
        'price' => 150,
        'square_meters' => 110,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'address' => 'Hauptstrasse 55, 10827 Berlino',
        'lat' => 52.4810,
        'lon' => 13.3469,
        'image_path' => 'apartment4.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 2,
        'user_id' => 5,
        'title' => 'Appartamento Storico nel Cuore della Città Vecchia',
        'slug' => 'appartamento-storico-citta-vecchia',
        'description' => 'Appartamento con charme storico situato nel cuore della città vecchia, vicino a monumenti e luoghi di interesse.',
        'price' => 220,
        'square_meters' => 150,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'address' => 'High Street 10, W3 6LJ Londra',
        'lat' => 51.5066,
        'lon' => -0.2643,
        'image_path' => 'apartment5.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Appartamento Moderno con Vista Panoramica',
        'slug' => 'appartamento-moderno-vista-panoramica',
        'description' => 'Un appartamento moderno con una vista panoramica mozzafiato sulla città.',
        'price' => 180,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'address' => 'Main Street 123, 11354 New York',
        'lat' => 40.7625,
        'lon' => -73.8314,
        'image_path' => 'apartment6.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 2,
        'title' => 'Loft Chic nel Cuore della Città',
        'slug' => 'loft-chic-citta',
        'description' => 'Un loft elegante e moderno situato nel centro della città, vicino ai principali centri di interesse.',
        'price' => 250,
        'square_meters' => 180,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'address' => 'George Street 456, M5A 2N3 Toronto',
        'lat' => 43.6606,
        'lon' => -79.3748,
        'image_path' => 'apartment7.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 3,
        'title' => 'Appartamento di Lusso con Piscina Privata',
        'slug' => 'appartamento-lusso-piscina-privata',
        'description' => 'Un appartamento di lusso con piscina privata, ideale per una vacanza di relax.',
        'price' => 300,
        'square_meters' => 220,
        'num_of_room' => 6,
        'num_of_bed' => 5,
        'num_of_bathroom' => 4,
        'address' => 'Chalkokondili 11, 106 77 Atene',
        'lat' => 37.9858,
        'lon' => 23.7303,
        'image_path' => 'apartment8.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 4,
        'title' => 'Casa Vacanze con Accesso Privato alla Spiaggia',
        'slug' => 'casa-vacanze-accesso-privato-spiaggia',
        'description' => 'Una casa vacanze con accesso privato alla spiaggia, perfetta per una vacanza al mare.',
        'price' => 280,
        'square_meters' => 200,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'address' => 'Pitt Street 69, 2000 Sydney',
        'lat' => -33.8638,
        'lon' => 151.2087,
        'image_path' => 'apartment9.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 4,
        'user_id' => 5,
        'title' => 'Appartamento con Vista Panoramica sulle Montagne',
        'slug' => 'appartamento-vista-panoramica-montagne',
        'description' => 'Un accogliente appartamento con una vista mozzafiato sulle montagne circostanti.',
        'price' => 150,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'address' => 'Weinbergstrasse 44, 8006 Zurigo',
        'lat' => 47.3809,
        'lon' => 8.5439,
        'image_path' => 'apartment10.jpg',
        'visible' => true,
    ],
];

return $data;

