<?php

$data = [
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Bellissimo Appartamento nel Centro',
        'slug' => 'bellissimo-appartamento-centro',
        'description' => 'Un appartamento spazioso e moderno nel cuore della città.',
        'price' => 50,
        'square_meters' => 80,
        'num_of_room' => 3,
        'num_of_bed' => 2,
        'num_of_bathroom' => 1,
        'country' => 'Italia',
        'street_address' => 'Via Roma 123',
        'city_name' => 'Roma',
        'postal_code' => '00040',
        'lat' => 41.7458,
        'lon' => 12.6508,
        'image_path' => 'images/apartment1.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 2,
        'user_id' => 2,
        'title' => 'Vista Mare Appartamento Deluxe',
        'slug' => 'vista-mare-appartamento-deluxe',
        'description' => 'Lussuoso appartamento con una vista mozzafiato sul mare.',
        'price' => 200,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'country' => 'Spagna',
        'street_address' => 'Calle del Mar 45',
        'city_name' => 'Barcelona',
        'postal_code' => '08001',
        'lat' => 41.3833,
        'lon' => 2.1833,
        'image_path' => 'images/apartment2.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 3,
        'user_id' => 3,
        'title' => 'Condominio Elegante con Giardino',
        'slug' => 'condominio-elegante-giardino',
        'description' => 'Appartamento situato in un condominio elegante con un bellissimo giardino comune.',
        'price' => 180,
        'square_meters' => 100,
        'num_of_room' => 3,
        'num_of_bed' => 2,
        'num_of_bathroom' => 2,
        'country' => 'Francia',
        'street_address' => 'Rue de la Paix 15',
        'city_name' => 'Parigi',
        'postal_code' => '75002',
        'lat' => 48.8695,
        'lon' => 2.3312,
        'image_path' => 'images/apartment3.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 4,
        'user_id' => 4,
        'title' => 'Villetta a Schiera con Giardino',
        'slug' => 'villetta-schiera-giardino',
        'description' => 'Villetta a schiera con spazioso giardino privato, perfetto per famiglie.',
        'price' => 150,
        'square_meters' => 110,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'country' => 'Germania',
        'street_address' => 'Hauptstrasse 55',
        'city_name' => 'Berlino',
        'postal_code' => '10827',
        'lat' => 52.4810,
        'lon' => 13.3469,
        'image_path' => 'images/apartment4.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 2,
        'user_id' => 5,
        'title' => 'Appartamento Storico nel Cuore della Città Vecchia',
        'slug' => 'appartamento-storico-citta-vecchia',
        'description' => 'Appartamento con charme storico situato nel cuore della città vecchia, vicino a monumenti e luoghi di interesse.',
        'price' => 220,
        'square_meters' => 150,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'country' => 'Regno Unito',
        'street_address' => 'High Street 10',
        'city_name' => 'Londra',
        'postal_code' => 'W3 6LJ',
        'lat' => 51.5066,
        'lon' => -0.2643,
        'image_path' => 'images/apartment5.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 2,
        'user_id' => 1,
        'title' => 'Appartamento Moderno con Vista Panoramica',
        'slug' => 'appartamento-moderno-vista-panoramica',
        'description' => 'Un appartamento moderno con una vista panoramica mozzafiato sulla città.',
        'price' => 180,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'country' => 'Stati Uniti',
        'street_address' => 'Main Street 123',
        'city_name' => 'New York',
        'postal_code' => '11354',
        'lat' => 40.7625,
        'lon' => -73.8314,
        'image_path' => 'images/apartment6.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 2,
        'title' => 'Loft Chic nel Cuore della Città',
        'slug' => 'loft-chic-citta',
        'description' => 'Un loft elegante e moderno situato nel centro della città, vicino ai principali centri di interesse.',
        'price' => 250,
        'square_meters' => 180,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'country' => 'Canada',
        'street_address' => 'George Street 456',
        'city_name' => 'Toronto',
        'postal_code' => 'M5A 2N3',
        'lat' => 43.6606,
        'lon' => -79.3748,
        'image_path' => 'images/apartment7.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 3,
        'title' => 'Appartamento di Lusso con Piscina Privata',
        'slug' => 'appartamento-lusso-piscina-privata',
        'description' => 'Un appartamento di lusso con piscina privata, ideale per una vacanza di relax.',
        'price' => 300,
        'square_meters' => 220,
        'num_of_room' => 6,
        'num_of_bed' => 5,
        'num_of_bathroom' => 4,
        'country' => 'Grecia',
        'street_address' => 'Chalkokondili 11',
        'city_name' => 'Atene',
        'postal_code' => '106 77',
        'lat' => 37.9858,
        'lon' => 23.7303,
        'image_path' => 'images/apartment8.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 1,
        'user_id' => 4,
        'title' => 'Casa Vacanze con Accesso Privato alla Spiaggia',
        'slug' => 'casa-vacanze-accesso-privato-spiaggia',
        'description' => 'Una casa vacanze con accesso privato alla spiaggia, perfetta per una vacanza al mare.',
        'price' => 280,
        'square_meters' => 200,
        'num_of_room' => 5,
        'num_of_bed' => 4,
        'num_of_bathroom' => 3,
        'country' => 'Australia',
        'street_address' => 'Pitt Street 69',
        'city_name' => 'Sydney',
        'postal_code' => '2000',
        'lat' => -33.8638,
        'lon' => 151.2087,
        'image_path' => 'images/apartment9.jpg',
        'visible' => true,
    ],
    [
        'type_id' => 4,
        'user_id' => 5,
        'title' => 'Appartamento con Vista Panoramica sulle Montagne',
        'slug' => 'appartamento-vista-panoramica-montagne',
        'description' => 'Un accogliente appartamento con una vista mozzafiato sulle montagne circostanti.',
        'price' => 150,
        'square_meters' => 120,
        'num_of_room' => 4,
        'num_of_bed' => 3,
        'num_of_bathroom' => 2,
        'country' => 'Svizzera',
        'street_address' => 'Weinbergstrasse 44',
        'city_name' => 'Zurigo',
        'postal_code' => '8006',
        'lat' => 47.3809,
        'lon' => 8.5439,
        'image_path' => 'images/apartment10.jpg',
        'visible' => true,
    ],
];

return $data;

